#
# Marvelous Morse Mentor
# Copyright 2021-2022 Leandro Motta Barros
# Licensed under the Apache License 2.0 (see the LICENSE file for details)
#

version: '2'
volumes:
    mmm-data:
services:
    mmm:
        build: ./mmm
        restart: unless-stopped
        labels:
            io.balena.features.sysfs: '1'
        devices:
            - /dev/i2c-1:/dev/i2c-1
            - /dev/mem:/dev/mem
        cap_add:
            - SYS_RAWIO
        volumes:
            - 'mmm-data:/data'
